### ISSUE TITLE
LIFO instead of FIFO

### ISSUE THREAD

**Issue by ronag** [jshttp/on-finished#18] opened 2016-07-09 19:49 UTC
It would be great if the calling order was LIFO (same as stack unwinding) instead of, how it is now, FIFO.

It could easily be accomplished by replacing `push` with `unshift`.

**Comment by dougwilson** [comment] 2016-07-09 19:57
This is a duplicate of #17 . This module will only run in the same order as even listeners, mainly because we are attaching event listeners. That internal array is just so if you use this module a lot on the same object, you won't get the too many event listeners warning. Ultimately, the order is only that of event listeners. You're welcome to publish your own module that goes in reverse, of course. I don't see why there cannot be a LIFO module and a FIFO module. At the very least, I wrote everything around the order this module works, so changing it is just not negotiable, I'm sorry.

If you publish another module,I can link to it in the readme as an alternative.

**Closed by dougwilson** 2016-07-09 19:57 UTC

**Comment by ronag** [comment] 2017-01-26 22:11
@dougwilson: https://github.com/nxtedition/on-finished/blob/master/README.md

**Comment by ggoodman** [comment] 2017-12-07 17:26
I've submitted a PR for optional LIFO ordering in #28.
