### ISSUE TITLE
unregister listener 

### ISSUE THREAD

**Issue by ronag** [jshttp/on-finished#22] opened 2017-01-29 16:52 UTC
Would be useful to be able to unregister a listener

**Comment by dougwilson** [comment] 2017-01-31 14:08
Hi @ronag seems like a good idea. I'm going to close this since it seems like a duplicate of https://github.com/jshttp/on-finished/issues/16#issuecomment-256815162 which we can use to track the request :)

**Closed by dougwilson** 2017-01-31 14:08 UTC
