### ISSUE TITLE
Module not found: Error: Can't resolve 'async_hooks'

### ISSUE THREAD

**Issue by SanGongHappy** [jshttp/on-finished#46] opened 2023-04-26 02:28 UTC
![U~R$T9 6)N0 $FRIJMZ VEG](https://user-images.githubusercontent.com/51526839/234450830-576552fd-0a92-4fc3-800a-acd34dff781b.png)

**Comment by dougwilson** [comment] 2023-05-10 14:03
Thank you both. I test this module in CI on almost every Node.js version without issue. If one of you can either provide a fix or provide instructions for how to replicate, thay would help, otherwise I'm not sure what can be done. The request is even in a try catch block too.

**Comment by SanGongHappy** [comment] 2023-05-11 01:22
> Thank you both. I test this module in CI on almost every Node.js version without issue. If one of you can either provide a fix or provide instructions for how to replicate, thay would help, otherwise I'm not sure what can be done. The request is even in a try catch block too.

My node version is 16.9.1. I posted the same question on Stackoverflow but didn't receive any responses. The issue is as follows:

```
warning  in ./node_modules/_on-finished@2.4.1@on-finished/index.js

Module not found: Error: Can't resolve 'async_hooks' in 'D:\project\xy2022\node_modules\_on-finished@2.4.1@on-finished'

 warning  in ./node_modules/_raw-body@2.5.1@raw-body/index.js

Module not found: Error: Can't resolve 'async_hooks' in 'D:\project\xy2022\node_modules\_raw-body@2.5.1@raw-body'
```
Although it runs normally, it feels awkward. My colleague and I have the same version of Node, but he doesn't get this error on his machine.

Reinstall node, upgrade to the latest version, install async_hooks, and add conditional statements in the two problematic files. There might be some issues with the implementation

```
function tryRequireAsyncHooks () {
  try {
    return require('async_hooks')
    // return {}
  } catch (e) {
    return {}
  }
}
```
Both sides of the code have errors in this function. I have a feeling that I haven't used these two plugins in my project. Changing 'return require('async_hooks')' to 'return {}' resolved the error.

**Comment by dougwilson** [comment] 2023-05-11 01:25
Thank you. Unfortunately that still doesn't explain how to reproduce the error/warning for me to help diagnose. And of course your provided fiz is not possible to accept, as you just... removed the require by commenting it out, meaning it break environments with `async_hooks`...

**Comment by dougwilson** [comment] 2023-05-11 01:27
I'm going to close this for now until someone can provide reproduction steps and we can reproduce the issue, particularly as no environment in CI has that error/warning at all, so maybe there is something broken with your environment outside of this module and this module is just revealing the broken environment? Thinking because you said your colleague doesn't have the issue (which is the same as me).

**Closed by dougwilson** 2023-05-11 01:27 UTC

**Comment by novNorthSea** [comment] 2025-01-12 02:08
In [remix-project](https://github.com/ethereum/remix-project.git), run  `yarn build` can reproduce the issue.
